set(_CATKIN_CURRENT_PACKAGE "autolabor_description")
set(autolabor_description_VERSION "0.0.0")
set(autolabor_description_MAINTAINER "jackey <jackey@todo.todo>")
set(autolabor_description_PACKAGE_FORMAT "1")
set(autolabor_description_BUILD_DEPENDS "joint_state_publisher" "robot_state_publisher" "rviz" "urdf" "xacro")
set(autolabor_description_BUILD_EXPORT_DEPENDS "joint_state_publisher" "robot_state_publisher" "rviz" "urdf" "xacro")
set(autolabor_description_BUILDTOOL_DEPENDS "catkin")
set(autolabor_description_BUILDTOOL_EXPORT_DEPENDS )
set(autolabor_description_EXEC_DEPENDS "joint_state_publisher" "robot_state_publisher" "rviz" "urdf" "xacro")
set(autolabor_description_RUN_DEPENDS "joint_state_publisher" "robot_state_publisher" "rviz" "urdf" "xacro")
set(autolabor_description_TEST_DEPENDS )
set(autolabor_description_DOC_DEPENDS )
set(autolabor_description_URL_WEBSITE "")
set(autolabor_description_URL_BUGTRACKER "")
set(autolabor_description_URL_REPOSITORY "")
set(autolabor_description_DEPRECATED "")