set(_CATKIN_CURRENT_PACKAGE "path_server")
set(path_server_VERSION "0.0.0")
set(path_server_MAINTAINER "colin <colin@todo.todo>")
set(path_server_PACKAGE_FORMAT "2")
set(path_server_BUILD_DEPENDS "roscpp" "tf" "message_generation")
set(path_server_BUILD_EXPORT_DEPENDS "roscpp" "tf")
set(path_server_BUILDTOOL_DEPENDS "catkin")
set(path_server_BUILDTOOL_EXPORT_DEPENDS )
set(path_server_EXEC_DEPENDS "message_runtime" "roscpp" "tf")
set(path_server_RUN_DEPENDS "message_runtime" "roscpp" "tf")
set(path_server_TEST_DEPENDS )
set(path_server_DOC_DEPENDS )
set(path_server_URL_WEBSITE "")
set(path_server_URL_BUGTRACKER "")
set(path_server_URL_REPOSITORY "")
set(path_server_DEPRECATED "")