set(_CATKIN_CURRENT_PACKAGE "autolabor_simulation_lidar")
set(autolabor_simulation_lidar_VERSION "0.0.1")
set(autolabor_simulation_lidar_MAINTAINER "Colin <shichunguo@gmail.com>")
set(autolabor_simulation_lidar_PACKAGE_FORMAT "1")
set(autolabor_simulation_lidar_BUILD_DEPENDS "roscpp" "nav_msgs" "tf")
set(autolabor_simulation_lidar_BUILD_EXPORT_DEPENDS "roscpp" "nav_msgs" "tf")
set(autolabor_simulation_lidar_BUILDTOOL_DEPENDS "catkin")
set(autolabor_simulation_lidar_BUILDTOOL_EXPORT_DEPENDS )
set(autolabor_simulation_lidar_EXEC_DEPENDS "roscpp" "nav_msgs" "tf")
set(autolabor_simulation_lidar_RUN_DEPENDS "roscpp" "nav_msgs" "tf")
set(autolabor_simulation_lidar_TEST_DEPENDS )
set(autolabor_simulation_lidar_DOC_DEPENDS )
set(autolabor_simulation_lidar_URL_WEBSITE "")
set(autolabor_simulation_lidar_URL_BUGTRACKER "")
set(autolabor_simulation_lidar_URL_REPOSITORY "")
set(autolabor_simulation_lidar_DEPRECATED "")