// Generated by gencpp from file autolabor_simulation_stage/Obstacle.msg
// DO NOT EDIT!


#ifndef AUTOLABOR_SIMULATION_STAGE_MESSAGE_OBSTACLE_H
#define AUTOLABOR_SIMULATION_STAGE_MESSAGE_OBSTACLE_H

#include <ros/service_traits.h>


#include <autolabor_simulation_stage/ObstacleRequest.h>
#include <autolabor_simulation_stage/ObstacleResponse.h>


namespace autolabor_simulation_stage
{

struct Obstacle
{

typedef ObstacleRequest Request;
typedef ObstacleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Obstacle
} // namespace autolabor_simulation_stage


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::autolabor_simulation_stage::Obstacle > {
  static const char* value()
  {
    return "16784fb8acead2e3b4470fa59f07d999";
  }

  static const char* value(const ::autolabor_simulation_stage::Obstacle&) { return value(); }
};

template<>
struct DataType< ::autolabor_simulation_stage::Obstacle > {
  static const char* value()
  {
    return "autolabor_simulation_stage/Obstacle";
  }

  static const char* value(const ::autolabor_simulation_stage::Obstacle&) { return value(); }
};


// service_traits::MD5Sum< ::autolabor_simulation_stage::ObstacleRequest> should match 
// service_traits::MD5Sum< ::autolabor_simulation_stage::Obstacle > 
template<>
struct MD5Sum< ::autolabor_simulation_stage::ObstacleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::autolabor_simulation_stage::Obstacle >::value();
  }
  static const char* value(const ::autolabor_simulation_stage::ObstacleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::autolabor_simulation_stage::ObstacleRequest> should match 
// service_traits::DataType< ::autolabor_simulation_stage::Obstacle > 
template<>
struct DataType< ::autolabor_simulation_stage::ObstacleRequest>
{
  static const char* value()
  {
    return DataType< ::autolabor_simulation_stage::Obstacle >::value();
  }
  static const char* value(const ::autolabor_simulation_stage::ObstacleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::autolabor_simulation_stage::ObstacleResponse> should match 
// service_traits::MD5Sum< ::autolabor_simulation_stage::Obstacle > 
template<>
struct MD5Sum< ::autolabor_simulation_stage::ObstacleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::autolabor_simulation_stage::Obstacle >::value();
  }
  static const char* value(const ::autolabor_simulation_stage::ObstacleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::autolabor_simulation_stage::ObstacleResponse> should match 
// service_traits::DataType< ::autolabor_simulation_stage::Obstacle > 
template<>
struct DataType< ::autolabor_simulation_stage::ObstacleResponse>
{
  static const char* value()
  {
    return DataType< ::autolabor_simulation_stage::Obstacle >::value();
  }
  static const char* value(const ::autolabor_simulation_stage::ObstacleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTOLABOR_SIMULATION_STAGE_MESSAGE_OBSTACLE_H
