set(_CATKIN_CURRENT_PACKAGE "ah100b")
set(ah100b_VERSION "0.1.0")
set(ah100b_MAINTAINER "colin <colin@todo.todo>")
set(ah100b_PACKAGE_FORMAT "1")
set(ah100b_BUILD_DEPENDS "roscpp" "serial" "sensor_msgs" "tf2" "tf" "tf")
set(ah100b_BUILD_EXPORT_DEPENDS "roscpp" "serial" "sensor_msgs" "tf2")
set(ah100b_BUILDTOOL_DEPENDS "catkin")
set(ah100b_BUILDTOOL_EXPORT_DEPENDS )
set(ah100b_EXEC_DEPENDS "roscpp" "serial" "sensor_msgs" "tf2")
set(ah100b_RUN_DEPENDS "roscpp" "serial" "sensor_msgs" "tf2")
set(ah100b_TEST_DEPENDS )
set(ah100b_DOC_DEPENDS )
set(ah100b_URL_WEBSITE "")
set(ah100b_URL_BUGTRACKER "")
set(ah100b_URL_REPOSITORY "")
set(ah100b_DEPRECATED "")