set(_CATKIN_CURRENT_PACKAGE "joy_to_twist")
set(joy_to_twist_VERSION "0.1.0")
set(joy_to_twist_MAINTAINER "Colin <Colin@todo.todo>")
set(joy_to_twist_PACKAGE_FORMAT "1")
set(joy_to_twist_BUILD_DEPENDS "roscpp" "geometry_msgs")
set(joy_to_twist_BUILD_EXPORT_DEPENDS "roscpp" "geometry_msgs")
set(joy_to_twist_BUILDTOOL_DEPENDS "catkin")
set(joy_to_twist_BUILDTOOL_EXPORT_DEPENDS )
set(joy_to_twist_EXEC_DEPENDS "roscpp" "geometry_msgs")
set(joy_to_twist_RUN_DEPENDS "roscpp" "geometry_msgs")
set(joy_to_twist_TEST_DEPENDS )
set(joy_to_twist_DOC_DEPENDS )
set(joy_to_twist_URL_WEBSITE "")
set(joy_to_twist_URL_BUGTRACKER "")
set(joy_to_twist_URL_REPOSITORY "")
set(joy_to_twist_DEPRECATED "")