set(_CATKIN_CURRENT_PACKAGE "path_rviz_plugin")
set(path_rviz_plugin_VERSION "0.0.0")
set(path_rviz_plugin_MAINTAINER "colin <colin@todo.todo>")
set(path_rviz_plugin_PACKAGE_FORMAT "1")
set(path_rviz_plugin_BUILD_DEPENDS "qtbase5-dev" "rviz" "path_server" "random_numbers")
set(path_rviz_plugin_BUILD_EXPORT_DEPENDS "libqt5-core" "libqt5-gui" "libqt5-widgets" "rviz" "path_server" "random_numbers")
set(path_rviz_plugin_BUILDTOOL_DEPENDS "catkin")
set(path_rviz_plugin_BUILDTOOL_EXPORT_DEPENDS )
set(path_rviz_plugin_EXEC_DEPENDS "libqt5-core" "libqt5-gui" "libqt5-widgets" "rviz" "path_server" "random_numbers")
set(path_rviz_plugin_RUN_DEPENDS "libqt5-core" "libqt5-gui" "libqt5-widgets" "rviz" "path_server" "random_numbers")
set(path_rviz_plugin_TEST_DEPENDS )
set(path_rviz_plugin_DOC_DEPENDS )
set(path_rviz_plugin_URL_WEBSITE "")
set(path_rviz_plugin_URL_BUGTRACKER "")
set(path_rviz_plugin_URL_REPOSITORY "")
set(path_rviz_plugin_DEPRECATED "")