#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/ntut-mit/catkin_ws/devel_isolated/cartographer_ros:/home/ntut-mit/catkin_ws/devel_isolated/cartographer_ros_msgs:/home/ntut-mit/catkin_ws/devel_isolated/camera_calibration:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_test_launch:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_simulation_object:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_simulation_stage:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_simulation_location:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_simulation_lidar:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_simulation_base:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_pro1_driver:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_navigation_launch:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_keyboard_control:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_description:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_canbus_driver:/home/ntut-mit/catkin_ws/devel_isolated/ah100b:/opt/ros/melodic:/home/ntut-mit/catkin_ws/devel_isolated/cartographer:/home/ntut-mit/catkin_ws/devel_isolated/ceres-solver"
export LD_LIBRARY_PATH="/home/ntut-mit/catkin_ws/devel_isolated/cartographer_ros_msgs/lib:/home/ntut-mit/catkin_ws/devel_isolated/camera_calibration/lib:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_test_launch/lib:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_simulation_object/lib:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_simulation_stage/lib:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_simulation_location/lib:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_simulation_lidar/lib:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_simulation_base/lib:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_pro1_driver/lib:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_navigation_launch/lib:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_keyboard_control/lib:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_description/lib:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_canbus_driver/lib:/home/ntut-mit/catkin_ws/devel_isolated/ah100b/lib:/opt/ros/melodic/lib:/home/ntut-mit/catkin_ws/devel_isolated/cartographer/lib:/home/ntut-mit/catkin_ws/devel_isolated/cartographer/lib/x86_64-linux-gnu:/home/ntut-mit/catkin_ws/devel_isolated/ceres-solver/lib:/home/ntut-mit/catkin_ws/devel_isolated/ceres-solver/lib/x86_64-linux-gnu"
export PATH="/opt/ros/melodic/bin:/home/ntut-mit/catkin_ws/devel_isolated/cartographer/bin:/home/ntut-mit/catkin_ws/devel_isolated/ceres-solver/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
export PKG_CONFIG_PATH="/home/ntut-mit/catkin_ws/devel_isolated/cartographer_ros_msgs/lib/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/camera_calibration/lib/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_test_launch/lib/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_simulation_object/lib/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_simulation_stage/lib/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_simulation_location/lib/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_simulation_lidar/lib/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_simulation_base/lib/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_pro1_driver/lib/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_navigation_launch/lib/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_keyboard_control/lib/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_description/lib/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_canbus_driver/lib/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/ah100b/lib/pkgconfig:/opt/ros/melodic/lib/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/cartographer/lib/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/cartographer/lib/x86_64-linux-gnu/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/ceres-solver/lib/pkgconfig:/home/ntut-mit/catkin_ws/devel_isolated/ceres-solver/lib/x86_64-linux-gnu/pkgconfig"
export PYTHONPATH="/home/ntut-mit/catkin_ws/devel_isolated/cartographer_ros_msgs/lib/python2.7/dist-packages:/home/ntut-mit/catkin_ws/devel_isolated/camera_calibration/lib/python2.7/dist-packages:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_simulation_stage/lib/python2.7/dist-packages:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_pro1_driver/lib/python2.7/dist-packages:/home/ntut-mit/catkin_ws/devel_isolated/autolabor_canbus_driver/lib/python2.7/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages:/home/ntut-mit/catkin_ws/devel_isolated/cartographer/lib/python2.7/dist-packages:/home/ntut-mit/catkin_ws/devel_isolated/ceres-solver/lib/python2.7/dist-packages"
export ROSLISP_PACKAGE_DIRECTORIES="/home/ntut-mit/catkin_ws/devel_isolated/cartographer_ros/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/ntut-mit/catkin_ws/src/autolabor/src/mapping/cartographer_ros/cartographer_ros:$ROS_PACKAGE_PATH"