set(_CATKIN_CURRENT_PACKAGE "wr_fslidar")
set(wr_fslidar_VERSION "0.0.0")
set(wr_fslidar_MAINTAINER "sctu <harrybot@aliyun.com>")
set(wr_fslidar_PACKAGE_FORMAT "1")
set(wr_fslidar_BUILD_DEPENDS "roscpp" "sensor_msgs" "std_msgs")
set(wr_fslidar_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs" "std_msgs")
set(wr_fslidar_BUILDTOOL_DEPENDS "catkin")
set(wr_fslidar_BUILDTOOL_EXPORT_DEPENDS )
set(wr_fslidar_EXEC_DEPENDS "roscpp" "sensor_msgs" "std_msgs")
set(wr_fslidar_RUN_DEPENDS "roscpp" "sensor_msgs" "std_msgs")
set(wr_fslidar_TEST_DEPENDS )
set(wr_fslidar_DOC_DEPENDS )
set(wr_fslidar_URL_WEBSITE "")
set(wr_fslidar_URL_BUGTRACKER "")
set(wr_fslidar_URL_REPOSITORY "")
set(wr_fslidar_DEPRECATED "")