set(_CATKIN_CURRENT_PACKAGE "autolabor_simulation_object")
set(autolabor_simulation_object_VERSION "0.0.1")
set(autolabor_simulation_object_MAINTAINER "Colin <shichunguo@gmail.com>")
set(autolabor_simulation_object_PACKAGE_FORMAT "1")
set(autolabor_simulation_object_BUILD_DEPENDS "roscpp" "tf" "interactive_markers" "visualization_msgs" "autolabor_simulation_stage")
set(autolabor_simulation_object_BUILD_EXPORT_DEPENDS "roscpp" "tf" "interactive_markers" "visualization_msgs" "autolabor_simulation_stage")
set(autolabor_simulation_object_BUILDTOOL_DEPENDS "catkin")
set(autolabor_simulation_object_BUILDTOOL_EXPORT_DEPENDS )
set(autolabor_simulation_object_EXEC_DEPENDS "roscpp" "tf" "interactive_markers" "visualization_msgs" "autolabor_simulation_stage")
set(autolabor_simulation_object_RUN_DEPENDS "roscpp" "tf" "interactive_markers" "visualization_msgs" "autolabor_simulation_stage")
set(autolabor_simulation_object_TEST_DEPENDS )
set(autolabor_simulation_object_DOC_DEPENDS )
set(autolabor_simulation_object_URL_WEBSITE "")
set(autolabor_simulation_object_URL_BUGTRACKER "")
set(autolabor_simulation_object_URL_REPOSITORY "")
set(autolabor_simulation_object_DEPRECATED "")