set(_CATKIN_CURRENT_PACKAGE "simulation_launch")
set(simulation_launch_VERSION "0.0.0")
set(simulation_launch_MAINTAINER "colin <colin@todo.todo>")
set(simulation_launch_PACKAGE_FORMAT "2")
set(simulation_launch_BUILD_DEPENDS )
set(simulation_launch_BUILD_EXPORT_DEPENDS )
set(simulation_launch_BUILDTOOL_DEPENDS "catkin")
set(simulation_launch_BUILDTOOL_EXPORT_DEPENDS )
set(simulation_launch_EXEC_DEPENDS )
set(simulation_launch_RUN_DEPENDS )
set(simulation_launch_TEST_DEPENDS )
set(simulation_launch_DOC_DEPENDS )
set(simulation_launch_URL_WEBSITE "")
set(simulation_launch_URL_BUGTRACKER "")
set(simulation_launch_URL_REPOSITORY "")
set(simulation_launch_DEPRECATED "")