set(_CATKIN_CURRENT_PACKAGE "location_fusion")
set(location_fusion_VERSION "0.0.1")
set(location_fusion_MAINTAINER "Colin <shichunguo@gmail.com>")
set(location_fusion_PACKAGE_FORMAT "1")
set(location_fusion_BUILD_DEPENDS "roscpp" "tf" "tf_conversions")
set(location_fusion_BUILD_EXPORT_DEPENDS "roscpp" "tf" "tf_conversions")
set(location_fusion_BUILDTOOL_DEPENDS "catkin")
set(location_fusion_BUILDTOOL_EXPORT_DEPENDS )
set(location_fusion_EXEC_DEPENDS "roscpp" "tf" "tf_conversions")
set(location_fusion_RUN_DEPENDS "roscpp" "tf" "tf_conversions")
set(location_fusion_TEST_DEPENDS )
set(location_fusion_DOC_DEPENDS )
set(location_fusion_URL_WEBSITE "")
set(location_fusion_URL_BUGTRACKER "")
set(location_fusion_URL_REPOSITORY "")
set(location_fusion_DEPRECATED "")