set(_CATKIN_CURRENT_PACKAGE "autolabor_test_launch")
set(autolabor_test_launch_VERSION "0.0.0")
set(autolabor_test_launch_MAINTAINER "colin <colin@todo.todo>")
set(autolabor_test_launch_PACKAGE_FORMAT "2")
set(autolabor_test_launch_BUILD_DEPENDS )
set(autolabor_test_launch_BUILD_EXPORT_DEPENDS )
set(autolabor_test_launch_BUILDTOOL_DEPENDS "catkin")
set(autolabor_test_launch_BUILDTOOL_EXPORT_DEPENDS )
set(autolabor_test_launch_EXEC_DEPENDS )
set(autolabor_test_launch_RUN_DEPENDS )
set(autolabor_test_launch_TEST_DEPENDS )
set(autolabor_test_launch_DOC_DEPENDS )
set(autolabor_test_launch_URL_WEBSITE "")
set(autolabor_test_launch_URL_BUGTRACKER "")
set(autolabor_test_launch_URL_REPOSITORY "")
set(autolabor_test_launch_DEPRECATED "")