// Generated by gencpp from file path_server/SetPathName.msg
// DO NOT EDIT!


#ifndef PATH_SERVER_MESSAGE_SETPATHNAME_H
#define PATH_SERVER_MESSAGE_SETPATHNAME_H

#include <ros/service_traits.h>


#include <path_server/SetPathNameRequest.h>
#include <path_server/SetPathNameResponse.h>


namespace path_server
{

struct SetPathName
{

typedef SetPathNameRequest Request;
typedef SetPathNameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPathName
} // namespace path_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_server::SetPathName > {
  static const char* value()
  {
    return "3572e731ca915997319cdf3e8b7f260b";
  }

  static const char* value(const ::path_server::SetPathName&) { return value(); }
};

template<>
struct DataType< ::path_server::SetPathName > {
  static const char* value()
  {
    return "path_server/SetPathName";
  }

  static const char* value(const ::path_server::SetPathName&) { return value(); }
};


// service_traits::MD5Sum< ::path_server::SetPathNameRequest> should match 
// service_traits::MD5Sum< ::path_server::SetPathName > 
template<>
struct MD5Sum< ::path_server::SetPathNameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_server::SetPathName >::value();
  }
  static const char* value(const ::path_server::SetPathNameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_server::SetPathNameRequest> should match 
// service_traits::DataType< ::path_server::SetPathName > 
template<>
struct DataType< ::path_server::SetPathNameRequest>
{
  static const char* value()
  {
    return DataType< ::path_server::SetPathName >::value();
  }
  static const char* value(const ::path_server::SetPathNameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_server::SetPathNameResponse> should match 
// service_traits::MD5Sum< ::path_server::SetPathName > 
template<>
struct MD5Sum< ::path_server::SetPathNameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_server::SetPathName >::value();
  }
  static const char* value(const ::path_server::SetPathNameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_server::SetPathNameResponse> should match 
// service_traits::DataType< ::path_server::SetPathName > 
template<>
struct DataType< ::path_server::SetPathNameResponse>
{
  static const char* value()
  {
    return DataType< ::path_server::SetPathName >::value();
  }
  static const char* value(const ::path_server::SetPathNameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_SERVER_MESSAGE_SETPATHNAME_H
