// Generated by gencpp from file path_server/SetPathNameRequest.msg
// DO NOT EDIT!


#ifndef PATH_SERVER_MESSAGE_SETPATHNAMEREQUEST_H
#define PATH_SERVER_MESSAGE_SETPATHNAMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path_server
{
template <class ContainerAllocator>
struct SetPathNameRequest_
{
  typedef SetPathNameRequest_<ContainerAllocator> Type;

  SetPathNameRequest_()
    : path_name()  {
    }
  SetPathNameRequest_(const ContainerAllocator& _alloc)
    : path_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_name_type;
  _path_name_type path_name;





  typedef boost::shared_ptr< ::path_server::SetPathNameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_server::SetPathNameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPathNameRequest_

typedef ::path_server::SetPathNameRequest_<std::allocator<void> > SetPathNameRequest;

typedef boost::shared_ptr< ::path_server::SetPathNameRequest > SetPathNameRequestPtr;
typedef boost::shared_ptr< ::path_server::SetPathNameRequest const> SetPathNameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_server::SetPathNameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_server::SetPathNameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_server::SetPathNameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_server::SetPathNameRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_server::SetPathNameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_server::SetPathNameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_server::SetPathNameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_server::SetPathNameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_server::SetPathNameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3572e731ca915997319cdf3e8b7f260b";
  }

  static const char* value(const ::path_server::SetPathNameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3572e731ca915997ULL;
  static const uint64_t static_value2 = 0x319cdf3e8b7f260bULL;
};

template<class ContainerAllocator>
struct DataType< ::path_server::SetPathNameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_server/SetPathNameRequest";
  }

  static const char* value(const ::path_server::SetPathNameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_server::SetPathNameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string path_name\n"
;
  }

  static const char* value(const ::path_server::SetPathNameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_server::SetPathNameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPathNameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_server::SetPathNameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_server::SetPathNameRequest_<ContainerAllocator>& v)
  {
    s << indent << "path_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_SERVER_MESSAGE_SETPATHNAMEREQUEST_H
