set(_CATKIN_CURRENT_PACKAGE "autolabor_simulation_base")
set(autolabor_simulation_base_VERSION "0.0.1")
set(autolabor_simulation_base_MAINTAINER "Colin <shichunguo@gmail.com>")
set(autolabor_simulation_base_PACKAGE_FORMAT "1")
set(autolabor_simulation_base_BUILD_DEPENDS "roscpp" "nav_msgs" "tf")
set(autolabor_simulation_base_BUILD_EXPORT_DEPENDS "roscpp" "nav_msgs" "tf")
set(autolabor_simulation_base_BUILDTOOL_DEPENDS "catkin")
set(autolabor_simulation_base_BUILDTOOL_EXPORT_DEPENDS )
set(autolabor_simulation_base_EXEC_DEPENDS "roscpp" "nav_msgs" "tf")
set(autolabor_simulation_base_RUN_DEPENDS "roscpp" "nav_msgs" "tf")
set(autolabor_simulation_base_TEST_DEPENDS )
set(autolabor_simulation_base_DOC_DEPENDS )
set(autolabor_simulation_base_URL_WEBSITE "")
set(autolabor_simulation_base_URL_BUGTRACKER "")
set(autolabor_simulation_base_URL_REPOSITORY "")
set(autolabor_simulation_base_DEPRECATED "")