set(_CATKIN_CURRENT_PACKAGE "autolabor_simulation_stage")
set(autolabor_simulation_stage_VERSION "0.0.1")
set(autolabor_simulation_stage_MAINTAINER "Colin <shichunguo@gmail.com>")
set(autolabor_simulation_stage_PACKAGE_FORMAT "1")
set(autolabor_simulation_stage_BUILD_DEPENDS "roscpp" "nav_msgs" "tf" "std_msgs" "message_generation")
set(autolabor_simulation_stage_BUILD_EXPORT_DEPENDS "roscpp" "nav_msgs" "tf" "std_msgs" "message_runtime")
set(autolabor_simulation_stage_BUILDTOOL_DEPENDS "catkin")
set(autolabor_simulation_stage_BUILDTOOL_EXPORT_DEPENDS )
set(autolabor_simulation_stage_EXEC_DEPENDS "roscpp" "nav_msgs" "tf" "std_msgs" "message_runtime")
set(autolabor_simulation_stage_RUN_DEPENDS "roscpp" "nav_msgs" "tf" "std_msgs" "message_runtime")
set(autolabor_simulation_stage_TEST_DEPENDS )
set(autolabor_simulation_stage_DOC_DEPENDS )
set(autolabor_simulation_stage_URL_WEBSITE "")
set(autolabor_simulation_stage_URL_BUGTRACKER "")
set(autolabor_simulation_stage_URL_REPOSITORY "")
set(autolabor_simulation_stage_DEPRECATED "")