set(_CATKIN_CURRENT_PACKAGE "marvelmind")
set(marvelmind_VERSION "0.0.1")
set(marvelmind_MAINTAINER "Colin <shichunguo@gmail.com>")
set(marvelmind_PACKAGE_FORMAT "1")
set(marvelmind_BUILD_DEPENDS "roscpp" "geometry_msgs" "message_generation")
set(marvelmind_BUILD_EXPORT_DEPENDS "roscpp" "geometry_msgs" "message_runtime")
set(marvelmind_BUILDTOOL_DEPENDS "catkin")
set(marvelmind_BUILDTOOL_EXPORT_DEPENDS )
set(marvelmind_EXEC_DEPENDS "roscpp" "geometry_msgs" "message_runtime")
set(marvelmind_RUN_DEPENDS "roscpp" "geometry_msgs" "message_runtime")
set(marvelmind_TEST_DEPENDS )
set(marvelmind_DOC_DEPENDS )
set(marvelmind_URL_WEBSITE "")
set(marvelmind_URL_BUGTRACKER "")
set(marvelmind_URL_REPOSITORY "")
set(marvelmind_DEPRECATED "")