set(_CATKIN_CURRENT_PACKAGE "tl740d")
set(tl740d_VERSION "0.0.0")
set(tl740d_MAINTAINER "colin <colin@todo.todo>")
set(tl740d_PACKAGE_FORMAT "2")
set(tl740d_BUILD_DEPENDS "roscpp" "sensor_msgs")
set(tl740d_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs")
set(tl740d_BUILDTOOL_DEPENDS "catkin")
set(tl740d_BUILDTOOL_EXPORT_DEPENDS )
set(tl740d_EXEC_DEPENDS "sensor_msgs" "roscpp")
set(tl740d_RUN_DEPENDS "sensor_msgs" "roscpp")
set(tl740d_TEST_DEPENDS )
set(tl740d_DOC_DEPENDS )
set(tl740d_URL_WEBSITE "")
set(tl740d_URL_BUGTRACKER "")
set(tl740d_URL_REPOSITORY "")
set(tl740d_DEPRECATED "")