set(_CATKIN_CURRENT_PACKAGE "record_path_planner")
set(record_path_planner_VERSION "0.0.0")
set(record_path_planner_MAINTAINER "colin <colin@todo.todo>")
set(record_path_planner_PACKAGE_FORMAT "2")
set(record_path_planner_BUILD_DEPENDS "costmap_2d" "nav_core" "pluginlib" "roscpp")
set(record_path_planner_BUILD_EXPORT_DEPENDS "costmap_2d" "nav_core" "pluginlib" "roscpp")
set(record_path_planner_BUILDTOOL_DEPENDS "catkin")
set(record_path_planner_BUILDTOOL_EXPORT_DEPENDS )
set(record_path_planner_EXEC_DEPENDS "costmap_2d" "nav_core" "pluginlib" "roscpp")
set(record_path_planner_RUN_DEPENDS "costmap_2d" "nav_core" "pluginlib" "roscpp")
set(record_path_planner_TEST_DEPENDS )
set(record_path_planner_DOC_DEPENDS )
set(record_path_planner_URL_WEBSITE "")
set(record_path_planner_URL_BUGTRACKER "")
set(record_path_planner_URL_REPOSITORY "")
set(record_path_planner_DEPRECATED "")