set(_CATKIN_CURRENT_PACKAGE "autolabor_canbus_driver")
set(autolabor_canbus_driver_VERSION "0.0.0")
set(autolabor_canbus_driver_MAINTAINER "Autolabor <support@autolabor.com.cn>")
set(autolabor_canbus_driver_PACKAGE_FORMAT "2")
set(autolabor_canbus_driver_BUILD_DEPENDS "roscpp" "tf" "std_msgs" "geometry_msgs" "nav_msgs" "message_generation")
set(autolabor_canbus_driver_BUILD_EXPORT_DEPENDS "roscpp" "tf" "std_msgs" "geometry_msgs" "nav_msgs")
set(autolabor_canbus_driver_BUILDTOOL_DEPENDS "catkin")
set(autolabor_canbus_driver_BUILDTOOL_EXPORT_DEPENDS )
set(autolabor_canbus_driver_EXEC_DEPENDS "message_runtime" "roscpp" "tf" "std_msgs" "geometry_msgs" "nav_msgs")
set(autolabor_canbus_driver_RUN_DEPENDS "message_runtime" "roscpp" "tf" "std_msgs" "geometry_msgs" "nav_msgs")
set(autolabor_canbus_driver_TEST_DEPENDS )
set(autolabor_canbus_driver_DOC_DEPENDS )
set(autolabor_canbus_driver_URL_WEBSITE "")
set(autolabor_canbus_driver_URL_BUGTRACKER "")
set(autolabor_canbus_driver_URL_REPOSITORY "")
set(autolabor_canbus_driver_DEPRECATED "")