set(_CATKIN_CURRENT_PACKAGE "autolabor_simulation_location")
set(autolabor_simulation_location_VERSION "0.0.0")
set(autolabor_simulation_location_MAINTAINER "colin <colin@todo.todo>")
set(autolabor_simulation_location_PACKAGE_FORMAT "2")
set(autolabor_simulation_location_BUILD_DEPENDS "roscpp" "tf" "geometry_msgs")
set(autolabor_simulation_location_BUILD_EXPORT_DEPENDS "roscpp" "tf" "geometry_msgs")
set(autolabor_simulation_location_BUILDTOOL_DEPENDS "catkin")
set(autolabor_simulation_location_BUILDTOOL_EXPORT_DEPENDS )
set(autolabor_simulation_location_EXEC_DEPENDS "roscpp" "tf" "geometry_msgs")
set(autolabor_simulation_location_RUN_DEPENDS "roscpp" "tf" "geometry_msgs")
set(autolabor_simulation_location_TEST_DEPENDS )
set(autolabor_simulation_location_DOC_DEPENDS )
set(autolabor_simulation_location_URL_WEBSITE "")
set(autolabor_simulation_location_URL_BUGTRACKER "")
set(autolabor_simulation_location_URL_REPOSITORY "")
set(autolabor_simulation_location_DEPRECATED "")